[package]
name = "sui_ptb_resolver"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
license = "Apache 2.0"
authors = ["Wormhole Labs"]

[dependencies]

[addresses]
sui_ptb_resolver = "0x0"

[dev-dependencies]

[dev-addresses]

