[package]
name = "wormhole_token_bridge_resolver"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
license = "Apache 2.0"
authors = ["Wormhole Labs"]

[dependencies]
sui_ptb_resolver = { local = "../sui_ptb_resolver" }

[addresses]
wormhole_token_bridge_resolver = "0x0"

[dev-dependencies]

[dev-addresses]

